### ISSUE TITLE
Can we tag with self hosted image

### ISSUE THREAD

**Issue by ranjitnadar** [ivanciric/propeller-ai#2]
Hi Propeller AI team Great work

Can we tag and scan self-hosted images.

**Comment by ivanciric** [comment]
Hi @ranjitnadar ,
You can send your images, wherever they are hosted, and you will get the tags back.
All you need to do is supply the image path, like in the example.php file.

Right now, propeller is trained pretty good on dogs, cars, male/female differential and a number of celebrities but, in time, it will learn to classify much more stuff.

If you have any more questions about the algorithm or anything else regarding the propeller engine itself, you can contact one of the actual authors https://github.com/goloskokovic.

Thank you for your interest!
